---
title: "FRED Analysis"
author: "DJJ"
date: "2023-07-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(fable)
library(scales)
library(janitor)
library(plotly)
```

## R Markdown

```{r}
# Three and Twelve Month Wages
rm(list=ls())
wages <- read_csv("./fred_median_wages.csv")
wages <- wages %>%
  filter(!is.na(FRBATLWGT3MMAUMHWGO), FRBATLWGT12MMUMHGO != "", FRBATLWGT12MMUMHGO %>% str_detect("[0-9]"))|> clean_names()
colnames(wages) <- c("date","three_median_wages","twelve_median_wages")
wages$twelve_median_wages <- as.numeric(wages$twelve_median_wages)
```
```{r}
summary(wages)
```

```{r}
# uigfull = Full Inflation quage
inflation <- read_csv("./fred_inflation.csv")
inflation <- inflation %>%
  filter(!is.na(UIGFULL), UIGFULL != "", UIGFULL %>% str_detect("[0-9]")) |> clean_names()|> select(date,uigfull)
inflation$uigfull <- as.numeric(inflation$uigfull)
  

```
```{r}
summary(inflation)
```


## Join wages and inflation

```{r}
wage_inflation <- inflation |> inner_join(wages)
summary(wage_inflation)
```
```{r}
writexl::write_xlsx(wage_inflation,path="./fred_wage_inflation.xlsx")
```

## Plot Inflation Data


```{r}
plot01 <-ggplot(wage_inflation) +
  geom_line(aes(x = date, y = uigfull), color = "steelblue", size = 1.2) +
  geom_smooth(aes(x = date, y = uigfull), color = "orange", size = 1, se = FALSE) +
  labs(title = "US Inflation Data Over Time",
       x = "Year",
       y = "Inflation Percent (%)") +
  theme_minimal() +
  theme(plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        legend.position = "none")
ggplotly(plot01)
```

```{r}
plot02 <-ggplot(wage_inflation) +
  geom_line(aes(x = date, y = three_median_wages), color = "steelblue", size = 1.2) +
  geom_smooth(aes(x = date, y = three_median_wages), color = "orange", size = 1, se = FALSE) +
  labs(title = "US Median Wages Over Time",
       x = "Year",
       y = "3 Month Median Wages") +
  theme_minimal() +
  theme(plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        legend.position = "none")
ggplotly(plot02)
```
```{r}
wage_inflation$wage2inflation <- wage_inflation$three_median_wages/wage_inflation$uigfull
```
```{r}
ggplot(wage_inflation) + geom_line(aes(x=date,y=wage2inflation))
```
```{r}
wage_inflation$inflation2wage <- wage_inflation$uigfull/wage_inflation$three_median_wages
```
```{r}
ggplot(wage_inflation) + geom_line(aes(x=date,y=inflation2wage,col="inflation2wage")) 

```


